default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: madluay
  password: madluay

development:
  <<: *default
  database: react_development

production:
  <<: *default
  database: react

staging:
  <<: *default
  database: react_staging
